import Head from "next/head";
import Image from "next/image";
import { Inter, Montserrat } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import SliderMain from "../components/slider";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  weight: ["400", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative container px-4 mx-auto lg:px-10 justify-center min-h-screen max-h-screen">
          <SliderMain></SliderMain>
        </div>
      </main>
    </>
  );
}
